spring.application.name=latex-compiler-service
server.port=8091

# Eureka Configuration
eureka.client.service-url.defaultZone=http://localhost:8761/eureka/
eureka.instance.prefer-ip-address=true

# Logging
logging.file.path=../logs/latex-compiler-service
logging.level.app=INFO
